// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             (unknown)
// source: api/proto/payment/v1/payment.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// PaymentAPIClient is the client API for PaymentAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PaymentAPIClient interface {
	// Create Payments. Payment can be created with positive or negative value.
	// Payments are made only in rubles(RUB).
	//
	// ```
	// Example request:
	//    sum: '99.99'
	//    company_name: 'AppStore'
	//    category: 'supermarkets'
	//    user_id: 1                // query param
	//    account_id: 1
	//    account_number: '123456'
	// ```
	//
	// ```
	// Example response:
	//    empty
	// Specific codes:
	//    * codes.InvalidArgument
	CreatePayment(ctx context.Context, in *CreatePaymentRequest, opts ...grpc.CallOption) (*CreatePaymentResponse, error)
	// Get user account balance by user ID.
	// By default the balance is given in rubles, if you want to convert the amount into another currency,
	// pass in query parameter ?currency={another_currency} another currency.
	// The name of the other currency should consist of 3 letters
	//
	// ```
	// Example request:
	//    id: 1           // path param
	//    currency: 'USD' // query param
	// ```
	//
	// ```
	// Example response:
	//    user_id: 1
	//    sum: '99.99'
	//    currency: 'USD'
	// ```
	//
	// Specific codes:
	//    * codes.InvalidArgument
	//    * codes.NotFound
	GetAccountByUserID(ctx context.Context, in *GetAccountByUserIDRequest, opts ...grpc.CallOption) (*GetAccountByUserIDResponse, error)
	// Transferring money between users.
	// Transferring money are made only in rubles(RUB).
	// If you try to transfer money to a user who does not exist or to a non-existent account, an error will be returned.
	//
	// ```
	// Example request:
	//    sum: '99.99'
	//    sender_id: 1
	//    sender_account_id: 1
	//    sender_account_number: '123'
	//    recipient_id: 2
	//    recipient_account_id: 1
	//    recipient_account_number: '123'
	//    recipient_name: 'Artem'
	// ```
	//
	// ```
	// Example response:
	//    sum: '99.99'
	//    recipient_id: 2
	//    recipient_name: 'Artem'
	// ```
	//
	// Specific codes:
	//    * codes.InvalidArgument
	//    * codes.NotFound
	TransferBetweenUsers(ctx context.Context, in *TransferBetweenUsersRequest, opts ...grpc.CallOption) (*TransferBetweenUsersResponse, error)
	// Get payments history by account id.
	// Query params:
	// - limit (default = 100)
	// - offset (default = 0)
	// - sort (only 'sum' and 'create_at', default = 'creat_at')
	// - order_by (only 'asc' or 'desc', default = 'desc')
	//
	// ```
	// Example request:
	//    user_id: 1      // path params
	//    limit: 5        // query params
	//    offset: 0       // query params
	//    sort: create_at // query params
	//    order_by: desc  // query params
	// ```
	//
	// ```
	// Example response:
	//    id: 1
	//    create_at: // FIXME: fix example time
	//    sum: '99.99'
	//    company_name: 2
	//    category: 'Artem'
	//    total: 1
	// ```
	//
	// Specific codes:
	//    * codes.InvalidArgument
	//    * codes.NotFound
	GetPaymentsHistoryByAccountID(ctx context.Context, in *GetPaymentsHistoryByAccountIDRequest, opts ...grpc.CallOption) (*GetPaymentsHistoryByAccountIDResponse, error)
	//  Get accounts by user id. Without paging and filters.
	//
	// ```
	// Example request:
	//    user_id: 1 // path params
	// ```
	//
	// ```
	// Example response:
	//    balance: '99.99'
	//    currency: 'RUB'
	//    account_number: '123'
	// ```
	//
	// Specific codes:
	//    * codes.InvalidArgument
	//    * codes.NotFound
	GetAccountsByUserID(ctx context.Context, in *GetAccountsByUserIDRequest, opts ...grpc.CallOption) (*GetAccountsByUserIDResponse, error)
}

type paymentAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewPaymentAPIClient(cc grpc.ClientConnInterface) PaymentAPIClient {
	return &paymentAPIClient{cc}
}

func (c *paymentAPIClient) CreatePayment(ctx context.Context, in *CreatePaymentRequest, opts ...grpc.CallOption) (*CreatePaymentResponse, error) {
	out := new(CreatePaymentResponse)
	err := c.cc.Invoke(ctx, "/api.proto.payment.v1.PaymentAPI/CreatePayment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentAPIClient) GetAccountByUserID(ctx context.Context, in *GetAccountByUserIDRequest, opts ...grpc.CallOption) (*GetAccountByUserIDResponse, error) {
	out := new(GetAccountByUserIDResponse)
	err := c.cc.Invoke(ctx, "/api.proto.payment.v1.PaymentAPI/GetAccountByUserID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentAPIClient) TransferBetweenUsers(ctx context.Context, in *TransferBetweenUsersRequest, opts ...grpc.CallOption) (*TransferBetweenUsersResponse, error) {
	out := new(TransferBetweenUsersResponse)
	err := c.cc.Invoke(ctx, "/api.proto.payment.v1.PaymentAPI/TransferBetweenUsers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentAPIClient) GetPaymentsHistoryByAccountID(ctx context.Context, in *GetPaymentsHistoryByAccountIDRequest, opts ...grpc.CallOption) (*GetPaymentsHistoryByAccountIDResponse, error) {
	out := new(GetPaymentsHistoryByAccountIDResponse)
	err := c.cc.Invoke(ctx, "/api.proto.payment.v1.PaymentAPI/GetPaymentsHistoryByAccountID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentAPIClient) GetAccountsByUserID(ctx context.Context, in *GetAccountsByUserIDRequest, opts ...grpc.CallOption) (*GetAccountsByUserIDResponse, error) {
	out := new(GetAccountsByUserIDResponse)
	err := c.cc.Invoke(ctx, "/api.proto.payment.v1.PaymentAPI/GetAccountsByUserID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PaymentAPIServer is the server API for PaymentAPI service.
// All implementations should embed UnimplementedPaymentAPIServer
// for forward compatibility
type PaymentAPIServer interface {
	// Create Payments. Payment can be created with positive or negative value.
	// Payments are made only in rubles(RUB).
	//
	// ```
	// Example request:
	//    sum: '99.99'
	//    company_name: 'AppStore'
	//    category: 'supermarkets'
	//    user_id: 1                // query param
	//    account_id: 1
	//    account_number: '123456'
	// ```
	//
	// ```
	// Example response:
	//    empty
	// Specific codes:
	//    * codes.InvalidArgument
	CreatePayment(context.Context, *CreatePaymentRequest) (*CreatePaymentResponse, error)
	// Get user account balance by user ID.
	// By default the balance is given in rubles, if you want to convert the amount into another currency,
	// pass in query parameter ?currency={another_currency} another currency.
	// The name of the other currency should consist of 3 letters
	//
	// ```
	// Example request:
	//    id: 1           // path param
	//    currency: 'USD' // query param
	// ```
	//
	// ```
	// Example response:
	//    user_id: 1
	//    sum: '99.99'
	//    currency: 'USD'
	// ```
	//
	// Specific codes:
	//    * codes.InvalidArgument
	//    * codes.NotFound
	GetAccountByUserID(context.Context, *GetAccountByUserIDRequest) (*GetAccountByUserIDResponse, error)
	// Transferring money between users.
	// Transferring money are made only in rubles(RUB).
	// If you try to transfer money to a user who does not exist or to a non-existent account, an error will be returned.
	//
	// ```
	// Example request:
	//    sum: '99.99'
	//    sender_id: 1
	//    sender_account_id: 1
	//    sender_account_number: '123'
	//    recipient_id: 2
	//    recipient_account_id: 1
	//    recipient_account_number: '123'
	//    recipient_name: 'Artem'
	// ```
	//
	// ```
	// Example response:
	//    sum: '99.99'
	//    recipient_id: 2
	//    recipient_name: 'Artem'
	// ```
	//
	// Specific codes:
	//    * codes.InvalidArgument
	//    * codes.NotFound
	TransferBetweenUsers(context.Context, *TransferBetweenUsersRequest) (*TransferBetweenUsersResponse, error)
	// Get payments history by account id.
	// Query params:
	// - limit (default = 100)
	// - offset (default = 0)
	// - sort (only 'sum' and 'create_at', default = 'creat_at')
	// - order_by (only 'asc' or 'desc', default = 'desc')
	//
	// ```
	// Example request:
	//    user_id: 1      // path params
	//    limit: 5        // query params
	//    offset: 0       // query params
	//    sort: create_at // query params
	//    order_by: desc  // query params
	// ```
	//
	// ```
	// Example response:
	//    id: 1
	//    create_at: // FIXME: fix example time
	//    sum: '99.99'
	//    company_name: 2
	//    category: 'Artem'
	//    total: 1
	// ```
	//
	// Specific codes:
	//    * codes.InvalidArgument
	//    * codes.NotFound
	GetPaymentsHistoryByAccountID(context.Context, *GetPaymentsHistoryByAccountIDRequest) (*GetPaymentsHistoryByAccountIDResponse, error)
	//  Get accounts by user id. Without paging and filters.
	//
	// ```
	// Example request:
	//    user_id: 1 // path params
	// ```
	//
	// ```
	// Example response:
	//    balance: '99.99'
	//    currency: 'RUB'
	//    account_number: '123'
	// ```
	//
	// Specific codes:
	//    * codes.InvalidArgument
	//    * codes.NotFound
	GetAccountsByUserID(context.Context, *GetAccountsByUserIDRequest) (*GetAccountsByUserIDResponse, error)
}

// UnimplementedPaymentAPIServer should be embedded to have forward compatible implementations.
type UnimplementedPaymentAPIServer struct {
}

func (UnimplementedPaymentAPIServer) CreatePayment(context.Context, *CreatePaymentRequest) (*CreatePaymentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePayment not implemented")
}
func (UnimplementedPaymentAPIServer) GetAccountByUserID(context.Context, *GetAccountByUserIDRequest) (*GetAccountByUserIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAccountByUserID not implemented")
}
func (UnimplementedPaymentAPIServer) TransferBetweenUsers(context.Context, *TransferBetweenUsersRequest) (*TransferBetweenUsersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TransferBetweenUsers not implemented")
}
func (UnimplementedPaymentAPIServer) GetPaymentsHistoryByAccountID(context.Context, *GetPaymentsHistoryByAccountIDRequest) (*GetPaymentsHistoryByAccountIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPaymentsHistoryByAccountID not implemented")
}
func (UnimplementedPaymentAPIServer) GetAccountsByUserID(context.Context, *GetAccountsByUserIDRequest) (*GetAccountsByUserIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAccountsByUserID not implemented")
}

// UnsafePaymentAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PaymentAPIServer will
// result in compilation errors.
type UnsafePaymentAPIServer interface {
	mustEmbedUnimplementedPaymentAPIServer()
}

func RegisterPaymentAPIServer(s grpc.ServiceRegistrar, srv PaymentAPIServer) {
	s.RegisterService(&PaymentAPI_ServiceDesc, srv)
}

func _PaymentAPI_CreatePayment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePaymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentAPIServer).CreatePayment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.proto.payment.v1.PaymentAPI/CreatePayment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentAPIServer).CreatePayment(ctx, req.(*CreatePaymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentAPI_GetAccountByUserID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAccountByUserIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentAPIServer).GetAccountByUserID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.proto.payment.v1.PaymentAPI/GetAccountByUserID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentAPIServer).GetAccountByUserID(ctx, req.(*GetAccountByUserIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentAPI_TransferBetweenUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransferBetweenUsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentAPIServer).TransferBetweenUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.proto.payment.v1.PaymentAPI/TransferBetweenUsers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentAPIServer).TransferBetweenUsers(ctx, req.(*TransferBetweenUsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentAPI_GetPaymentsHistoryByAccountID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPaymentsHistoryByAccountIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentAPIServer).GetPaymentsHistoryByAccountID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.proto.payment.v1.PaymentAPI/GetPaymentsHistoryByAccountID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentAPIServer).GetPaymentsHistoryByAccountID(ctx, req.(*GetPaymentsHistoryByAccountIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentAPI_GetAccountsByUserID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAccountsByUserIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentAPIServer).GetAccountsByUserID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.proto.payment.v1.PaymentAPI/GetAccountsByUserID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentAPIServer).GetAccountsByUserID(ctx, req.(*GetAccountsByUserIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PaymentAPI_ServiceDesc is the grpc.ServiceDesc for PaymentAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PaymentAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.proto.payment.v1.PaymentAPI",
	HandlerType: (*PaymentAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreatePayment",
			Handler:    _PaymentAPI_CreatePayment_Handler,
		},
		{
			MethodName: "GetAccountByUserID",
			Handler:    _PaymentAPI_GetAccountByUserID_Handler,
		},
		{
			MethodName: "TransferBetweenUsers",
			Handler:    _PaymentAPI_TransferBetweenUsers_Handler,
		},
		{
			MethodName: "GetPaymentsHistoryByAccountID",
			Handler:    _PaymentAPI_GetPaymentsHistoryByAccountID_Handler,
		},
		{
			MethodName: "GetAccountsByUserID",
			Handler:    _PaymentAPI_GetAccountsByUserID_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/payment/v1/payment.proto",
}
