name: CI/CD

on:
  push:
    paths:
      - 'rest-on-grpc-gateway/*'
    branches:
      - '*'
  pull_request:
    paths:
      - 'rest-on-grpc-gateway/*'
    branches:
      - '*'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.45.2
          working-directory: rest-on-grpc-gateway/

  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.17

      - name: Checkout repository.
        uses: actions/checkout@v2

      - name: Start test.
        run: make test
