USER_HOST: "0.0.0.0"
USER_GRPC_PORT: "8080"
USER_GRPC_GW_PORT: "8081"
USER_MIGRATIONS_DIR: "./modules/user/migrations"

PAYMENT_HOST: "0.0.0.0"
PAYMENT_GRPC_PORT: "8090"
PAYMENT_GRPC_GW_PORT: "8091"
PAYMENT_MIGRATIONS_DIR: "./modules/payment/migrations"

DB_HOST: "localhost"
DB_PORT: "5432"
DB_NAME: "postgres"
DB_USER: "postgres"
DB_PASSWORD: "postgres"
DB_SSL_MODE: "disable"